# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 13 is conviniet
# when copying and pasting from another recipe, but not really needed.
{% set name = "lame" %}
{% set version = "None" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/sourceforge/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cf5ce27d21490c24eedf91e0ac2bc4a748ba8f4eb20cb7c1fc9442d2d580008
  patches:
    - libmp3lame.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # seems to be minor version compatibility
    # https://abi-laboratory.pro/tracker/timeline/lame/
    - {{ pin_subpackage('lame', max_pin='x.x') }}
  missing_dso_whitelist:
    - "*ncurses*"   # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libiconv  # [osx]

test:
  commands:
    - lame --genre-list testcase.mp3

about:
  home: https://lame.sourceforge.io/
  license: LGPL
  license_file: LICENSE
  summary: 'High quality MPEG Audio Layer III (MP3) encoder'

  # The remaining entries in this section are optional, but recommended
  description: |
    LAME is a high quality MPEG Audio Layer III (MP3) encoder licensed under the LGPL.
    Today, LAME is considered the best MP3 encoder at mid-high bitrates and at VBR, mostly
    thanks to the dedicated work of its developers and the open source licensing model
    that allowed the project to tap into engineering resources from all around the world.
  doc_url: http://lame.sourceforge.net/using.php
  dev_url: https://svn.code.sf.net/p/lame/svn/trunk/lame/

extra:
  recipe-maintainers:
    - soumith
