appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: r6Pg7vltWjvcYEqPVuXargX+INI3TNKwWuCZZAUuL0U/zty0rGmj28E2StMCCL1eUVlSVjt8S/z53RpXxVBGmHoId65A1okcoHPDLXLjRNjEkt6gdYlRZjbeJJP6nVc1kbsBWc4DmP41pl97uxPItyGNWBuw+10BuQmROBi+RHI89RqtO5pBFfdZDIHHsgXKxgu3eFODxss2vx43kmMGa6yyVkO2LkR/oWneSosa58nESgv1f63QGwafM+5M0KQ79SBCWyFg3RyiZOaQclL7pglGc2+CskBN2Jx/dVwQSk4FAlflpd0bPxTe0MK4j9uTx5nfiKKm4HdMJXwmO/8y+muH2sBcLQFB+CnMxmAsVe9E56Fvoxetisy7NzB2rAnP26CHTtUgizNRo5S8z4LXIskgFWUth7I2aUKKGdfSeZf/W+szhCdNGvjUsarXASfNkkFLZUR327d+Z2AdcvAvgRswaYGXn5zoEGA7NFRiUTk/XRNPQ8rZHShK+Kw331Ari/Q0N8tT4ERDya2WGWM1NaE2HHoRpiAylmhAI9taDYeYfAs94ZJpToBCqKHqsqBltSZN+eONp+zDIc9fMkC0jMxglyCXq57ZHZxi9mbX1nmF+6uMMmiVnpoyZLv9aOE7Jm8LclfrsvXjcQeJj8aBkBMn7yrjKJ9/ASbdgornlsk=}
